#!/usr/bin/env node
/**
 * Convierte data/productos.csv en fichas .md dentro de src/content/products/.
 * Idempotente: borra ficheros generados previamente (auto-generated: true en frontmatter)
 * antes de regenerar, para mantener limpia la colección.
 *
 * Uso: node scripts/csv-to-md.mjs
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, unlinkSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CSV_PATH = join(ROOT, 'data', 'productos.csv');
const OUT_DIR = join(ROOT, 'src', 'content', 'products');

// Map de categorías padre del CSV → forma canónica del enum del schema
const CATEGORIA_PADRE_MAP = {
  'INDUSTRIA EN GENERAL': 'Industria en general',
  'INDUSTRIA ALIMENTARIA': 'Industria alimentaria',
  'LINEA ECOLOGICA': 'Línea ecológica',
  'SUMINISTRO INDUSTRIAL': 'Suministro industrial',
};

// Map de categorías (mostrables) — formato Title Case con tildes
const CATEGORIA_MAP = {
  'DETERGENTES Y DESENGRASANTES': 'Detergentes y desengrasantes',
  'HIGIENE DE MANOS': 'Higiene de manos',
  'TALLERES MANTENIMIENTO Y AUTOMOCION': 'Talleres, mantenimiento y automoción',
  'HOSTELERIA': 'Hostelería',
  'CONSTRUCCION Y PINTURAS': 'Construcción y pinturas',
  'DETERGENTES DESENGRASANTES Y BIOCIDAS': 'Detergentes, desengrasantes y biocidas',
  'ADITIVOS E HIGIENIZANTES ESPECIALES': 'Aditivos e higienizantes especiales',
};

function slugify(str) {
  return str
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\//g, '-')
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

function parseCSV(text) {
  const [header, ...rows] = text
    .split(/\r?\n/)
    .filter((l) => l.trim().length > 0);
  const cols = header.split(';').map((c) => c.trim());
  return rows.map((row) => {
    const values = row.split(';').map((v) => v.trim());
    return Object.fromEntries(cols.map((c, i) => [c, values[i] ?? '']));
  });
}

function yamlEscape(s) {
  if (s == null) return '""';
  // Comillas dobles, escape básico
  return `"${String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function buildMarkdown({ nombre, descripcion, categoriaPadre, categoria, ref }) {
  const lines = [
    '---',
    'autoGenerated: true',
    `nombre: ${yamlEscape(nombre)}`,
    `ref: ${yamlEscape(ref)}`,
    `categoriaPadre: ${yamlEscape(categoriaPadre)}`,
    `categoria: ${yamlEscape(categoria)}`,
    `descripcion: ${yamlEscape(descripcion || nombre)}`,
    '---',
    '',
    `## ${nombre}`,
    '',
    descripcion ? descripcion : '_Ficha técnica disponible bajo petición._',
    '',
    '> Para fichas técnicas, de seguridad o condiciones de suministro, contacta con el equipo comercial.',
    '',
  ];
  return lines.join('\n');
}

function main() {
  if (!existsSync(CSV_PATH)) {
    console.error(`[!] CSV no encontrado: ${CSV_PATH}`);
    process.exit(1);
  }
  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

  // Limpia archivos previamente auto-generados (y ejemplos del scaffold)
  for (const file of readdirSync(OUT_DIR)) {
    const full = join(OUT_DIR, file);
    if (!file.endsWith('.md')) continue;
    const content = readFileSync(full, 'utf8');
    if (file.startsWith('ejemplo-') || /^autoGenerated:\s*true/m.test(content)) {
      unlinkSync(full);
    }
  }

  const csv = readFileSync(CSV_PATH, 'utf8');
  const rows = parseCSV(csv);

  let written = 0;
  const seen = new Set();

  for (const row of rows) {
    const nombre = row['Nombre'];
    if (!nombre) continue;
    const descripcion = row['Descripcion corta'] || '';
    const catPadreRaw = row['Categoria padre'];
    const catRaw = row['Categoria'];
    const id = row['ID'];

    const categoriaPadre = CATEGORIA_PADRE_MAP[catPadreRaw];
    const categoria = CATEGORIA_MAP[catRaw];

    if (!categoriaPadre || !categoria) {
      // Ignora filas de categorías padre vacías (LINEA ECOLOGICA, SUMINISTRO INDUSTRIAL)
      continue;
    }

    const slug = `${id.toLowerCase()}-${slugify(nombre)}`;
    if (seen.has(slug)) continue;
    seen.add(slug);

    const md = buildMarkdown({
      nombre,
      descripcion,
      categoriaPadre,
      categoria,
      ref: id,
    });
    writeFileSync(join(OUT_DIR, `${slug}.md`), md, 'utf8');
    written++;
  }

  console.log(`[✓] Generadas ${written} fichas de producto en ${OUT_DIR}`);
}

main();
